<a href="https://colab.research.google.com/github/galahad20/assignment_Data_Manipulation/blob/main/ASSIGNMENT_TEMP_DE14_DAY11_DIMAS_ABIAN_IHSAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Data Manipulation
by `Dimas Abian Ihsan`

**Dibimbing - Batch 14 | DE**

**Riwayat Implementasi Github Collaboration Flow
 :** https://github.com/galahad20/assignment_Data_Manipulation

Objectives
- Student mampu melakukan filter dan select data menggunakan pandas
- Student mampu melakukan group by dan agregasi data
- Student mampu melakukan join/merge antar tabel
- Student mampu melakukan operasi dataframe
- Student mampu melakukan transformasi dan feature engineering

## Persiapan

### Import Library

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

%matplotlib inline
print('Libraries Loaded!')

Libraries Loaded!

### Import Dataset

In [3]:
#import data customers
cust_path = '/content/drive/MyDrive/dibimbing/assignment/dataset-day11/customers.csv'
cust = pd.read_csv(cust_path)
cust.head()

,customer_id,customer_name,email,city,province,registration_date,membership_tier
0,C001,Andi Wijaya,andi.wijaya@email.com,Jakarta,DKI Jakarta,2024-01-15,Gold
1,C002,Budi Santoso,budi.santoso@email.com,Bandung,Jawa Barat,2024-02-20,Silver
2,C003,Citra Dewi,citra.dewi@email.com,Surabaya,Jawa Timur,2024-03-10,Gold
3,C004,Dian Pratama,dian.pratama@email.com,Medan,Sumatera Utara,2024-04-05,Bronze
4,C005,Eka Putri,eka.putri@email.com,Jakarta,DKI Jakarta,2024-05-12,Platinum

In [4]:
#import data orders
order_path = '/content/drive/MyDrive/dibimbing/assignment/dataset-day11/orders.csv'
order = pd.read_csv(order_path)
order.head()

,order_id,customer_id,customer_name,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city,payment_method,order_status
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered
2,ORD0003,C003,Citra Dewi,2025-01-07,P003,Sepatu Nike,Fashion,1,1500000,0,1500000,Surabaya,E-Wallet,Delivered
3,ORD0004,C001,Andi Wijaya,2025-01-08,P004,Mouse Logitech,Electronics,3,350000,10,945000,Jakarta,Credit Card,Delivered
4,ORD0005,C004,Dian Pratama,2025-01-09,P005,Tas Ransel,Fashion,2,450000,5,855000,Medan,COD,Delivered

In [5]:
#import data products
prod_path = '/content/drive/MyDrive/dibimbing/assignment/dataset-day11/products.csv'
prod = pd.read_csv(prod_path)
prod.head()

,product_id,product_name,category,brand,unit_cost,unit_price,stock_qty
0,P001,Laptop ASUS,Electronics,ASUS,10000000,12500000,50
1,P002,Smartphone Samsung,Electronics,Samsung,6800000,8500000,100
2,P003,Sepatu Nike,Fashion,Nike,1200000,1500000,200
3,P004,Mouse Logitech,Electronics,Logitech,280000,350000,500
4,P005,Tas Ransel,Fashion,Local,360000,450000,150

### Cek info kolom, null, dan duplicate

In [8]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        20 non-null     object
 1   customer_name      20 non-null     object
 2   email              20 non-null     object
 3   city               20 non-null     object
 4   province           20 non-null     object
 5   registration_date  20 non-null     object
 6   membership_tier    20 non-null     object
dtypes: object(7)
memory usage: 1.2+ KB

In [10]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     object
 1   customer_id     50 non-null     object
 2   customer_name   50 non-null     object
 3   order_date      50 non-null     object
 4   product_id      50 non-null     object
 5   product_name    50 non-null     object
 6   category        50 non-null     object
 7   quantity        50 non-null     int64
 8   unit_price      50 non-null     int64
 9   discount_pct    50 non-null     int64
 10  total_amount    50 non-null     int64
 11  city            50 non-null     object
 12  payment_method  50 non-null     object
 13  order_status    50 non-null     object
dtypes: int64(4), object(10)
memory usage: 5.6+ KB

In [9]:
prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    15 non-null     object
 1   product_name  15 non-null     object
 2   category      15 non-null     object
 3   brand         15 non-null     object
 4   unit_cost     15 non-null     int64
 5   unit_price    15 non-null     int64
 6   stock_qty     15 non-null     int64
dtypes: int64(3), object(4)
memory usage: 972.0+ bytes

In [15]:
#cek null dan duplicate
list_df = [prod, cust, order]
for df in list_df:
  print(df.isna().sum())

print(f"--------------------")
for df in list_df:
  print(df.duplicated().sum())

product_id      0
product_name    0
category        0
brand           0
unit_cost       0
unit_price      0
stock_qty       0
dtype: int64
customer_id          0
customer_name        0
email                0
city                 0
province             0
registration_date    0
membership_tier      0
dtype: int64
order_id          0
customer_id       0
customer_name     0
order_date        0
product_id        0
product_name      0
category          0
quantity          0
unit_price        0
discount_pct      0
total_amount      0
city              0
payment_method    0
order_status      0
dtype: int64
--------------------
0
0
0

## Filter and select

### Filter orders yang memiliki category = “Electronics”

In [7]:
order[order['category']== 'Electronics']

,order_id,customer_id,customer_name,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city,payment_method,order_status
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered
3,ORD0004,C001,Andi Wijaya,2025-01-08,P004,Mouse Logitech,Electronics,3,350000,10,945000,Jakarta,Credit Card,Delivered
5,ORD0006,C005,Eka Putri,2025-01-10,P006,Headphone Sony,Electronics,1,2500000,15,2125000,Jakarta,Credit Card,Delivered
7,ORD0008,C006,Fajar Nugroho,2025-01-12,P008,Keyboard Mechanical,Electronics,1,1200000,10,1080000,Yogyakarta,E-Wallet,Delivered
10,ORD0011,C008,Hendra Kusuma,2025-01-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Makassar,Bank Transfer,Delivered
11,ORD0012,C009,Indah Permata,2025-01-16,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Denpasar,E-Wallet,Delivered
16,ORD0017,C011,Kartika Sari,2025-01-21,P004,Mouse Logitech,Electronics,2,350000,5,665000,Batam,COD,Delivered
18,ORD0019,C002,Budi Santoso,2025-01-23,P006,Headphone Sony,Electronics,1,2500000,10,2250000,Bandung,Bank Transfer,Delivered
20,ORD0021,C014,Nanda Putra,2025-01-25,P008,Keyboard Mechanical,Electronics,1,1200000,0,1200000,Banjarmasin,COD,Delivered
25,ORD0026,C007,Gita Sari,2025-01-30,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Semarang,Credit Card,Delivered
27,ORD0028,C008,Hendra Kusuma,2025-02-01,P002,Smartphone Samsung,Electronics,1,8500000,0,8500000,Makassar,E-Wallet,Delivered
31,ORD0032,C010,Joko Widodo,2025-02-05,P004,Mouse Logitech,Electronics,4,350000,10,1260000,Palembang,E-Wallet,Delivered
34,ORD0035,C011,Kartika Sari,2025-02-08,P006,Headphone Sony,Electronics,1,2500000,10,2250000,Batam,Bank Transfer,Delivered
37,ORD0038,C005,Eka Putri,2025-02-11,P008,Keyboard Mechanical,Electronics,2,1200000,10,2160000,Jakarta,Credit Card,Delivered
41,ORD0042,C006,Fajar Nugroho,2025-02-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Yogyakarta,Credit Card,Delivered
43,ORD0044,C003,Citra Dewi,2025-02-17,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Surabaya,E-Wallet,Delivered
46,ORD0047,C017,Qori Amalia,2025-02-20,P004,Mouse Logitech,Electronics,1,350000,0,350000,Cirebon,Bank Transfer,Delivered

### Filter orders dengan total_amount > 5000000

In [18]:
order[order['total_amount'] > 5000000]

,order_id,customer_id,customer_name,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city,payment_method,order_status
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered
10,ORD0011,C008,Hendra Kusuma,2025-01-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Makassar,Bank Transfer,Delivered
11,ORD0012,C009,Indah Permata,2025-01-16,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Denpasar,E-Wallet,Delivered
25,ORD0026,C007,Gita Sari,2025-01-30,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Semarang,Credit Card,Delivered
27,ORD0028,C008,Hendra Kusuma,2025-02-01,P002,Smartphone Samsung,Electronics,1,8500000,0,8500000,Makassar,E-Wallet,Delivered
41,ORD0042,C006,Fajar Nugroho,2025-02-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Yogyakarta,Credit Card,Delivered
43,ORD0044,C003,Citra Dewi,2025-02-17,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Surabaya,E-Wallet,Delivered

### Select hanya kolom order_id, customer_name, product_name, total_amount

In [20]:
order[['order_id', 'customer_name', 'product_name', 'total_amount']]

   order_id   customer_name         product_name  total_amount
0   ORD0001     Andi Wijaya          Laptop ASUS      11250000
1   ORD0002    Budi Santoso   Smartphone Samsung      16150000
2   ORD0003      Citra Dewi          Sepatu Nike       1500000
3   ORD0004     Andi Wijaya       Mouse Logitech        945000
4   ORD0005    Dian Pratama           Tas Ransel        855000
5   ORD0006       Eka Putri       Headphone Sony       2125000
6   ORD0007    Budi Santoso           Dress Zara        850000
7   ORD0008   Fajar Nugroho  Keyboard Mechanical       1080000
8   ORD0009       Gita Sari         Celana Jeans        760000
9   ORD0010      Citra Dewi           Jam Tangan       1200000
10  ORD0011   Hendra Kusuma          Laptop ASUS      11250000
11  ORD0012   Indah Permata   Smartphone Samsung       8075000
12  ORD0013     Joko Widodo          Sepatu Nike       2700000
13  ORD0014     Andi Wijaya         Skincare Set        550000
14  ORD0015    Dian Pratama          Parfum Dior       1870000
15  ORD0016       Eka Putri     Kacamata Ray-Ban       3150000
16  ORD0017    Kartika Sari       Mouse Logitech        665000
17  ORD0018    Lukman Hakim           Tas Ransel        450000
18  ORD0019    Budi Santoso       Headphone Sony       2250000
19  ORD0020      Maya Putri           Dress Zara       1615000
20  ORD0021     Nanda Putra  Keyboard Mechanical       1200000
21  ORD0022      Citra Dewi          Lipstik MAC       1215000
22  ORD0023       Oscar Tan         Celana Jeans        380000
23  ORD0024   Fajar Nugroho           Jam Tangan       1020000
24  ORD0025       Putri Ayu         Dompet Kulit       1300000
25  ORD0026       Gita Sari          Laptop ASUS      11250000
26  ORD0027     Qori Amalia         Skincare Set       1045000
27  ORD0028   Hendra Kusuma   Smartphone Samsung       8500000
28  ORD0029    Rizky Fauzan          Parfum Dior       1980000
29  ORD0030   Indah Permata          Sepatu Nike       1425000
30  ORD0031      Sinta Dewi     Kacamata Ray-Ban       2975000
31  ORD0032     Joko Widodo       Mouse Logitech       1260000
32  ORD0033  Taufik Hidayat          Lipstik MAC        900000
33  ORD0034     Andi Wijaya           Tas Ransel        427500
34  ORD0035    Kartika Sari       Headphone Sony       2250000
35  ORD0036    Dian Pratama         Dompet Kulit        650000
36  ORD0037    Lukman Hakim           Dress Zara        807500
37  ORD0038       Eka Putri  Keyboard Mechanical       2160000
38  ORD0039      Maya Putri         Celana Jeans       1020000
39  ORD0040    Budi Santoso           Jam Tangan       1200000
40  ORD0041     Nanda Putra         Skincare Set        522500
41  ORD0042   Fajar Nugroho          Laptop ASUS      11250000
42  ORD0043       Oscar Tan          Parfum Dior       2200000
43  ORD0044      Citra Dewi   Smartphone Samsung       8075000
44  ORD0045       Putri Ayu     Kacamata Ray-Ban       3150000
45  ORD0046       Gita Sari          Sepatu Nike       2550000
46  ORD0047     Qori Amalia       Mouse Logitech        350000
47  ORD0048   Hendra Kusuma          Lipstik MAC       1710000
48  ORD0049    Rizky Fauzan           Tas Ransel        810000
49  ORD0050   Indah Permata         Dompet Kulit        650000